### ISSUE TITLE
Meeting recordings - right to forget

### ISSUE THREAD

**Issue by prisae** [simpeg/community#13]
It started on Slack and was later discussed in the meeting of 30 June 2021.

The idea is to unlist the meeting recordings after a certain time, and remove them from the public completely after another time. Rough time-frames and other important points that were mentioned:

- Unlist videos after 6 months - 1 year
- Remove from public after ~2 years (they can be kept on YouTube, just private)
- Possibility to flag meetings with interesting presentations for longer
- An idea was to extract the text (caption) from the videos, so one could ctrl-f for interesting ideas.

**Comment by lheagy** [comment]
Thanks for raising this! Is anyone aware of how to extract text / caption from youtube (ideally for free??)

**Comment by prisae** [comment]
@domfournier had the idea, and I think @thast said that he has actually done that before.

**Comment by lheagy** [comment]
In the [SimPEG meeting on Sept 29](https://curvenote.com/@simpeg/meeting-notes/2021-09-29), we decided to unlist videos after 1 year. All SimPEG meetings up to Sept 30, 2020 have now been unlisted. I will put a reminder in my calendar to do this annually, so videos may be up and public for as long as 2 years. Unlisted means that if there are links to these videos, that they will still work, but unlisted videos are less discoverable and won't show up by default on the geosci page
