### ISSUE TITLE
SimPEG seminars

### ISSUE THREAD

**Issue by lheagy** [simpeg/community#9]
In the SimPEG meeting on [2021-06-16](https://curvenote.com/@simpeg/meeting-notes/2021-06-16/edit), we talked about the idea of having monthly SimPEG seminars. Suggested format: 
- 1 hour time-slot, recorded on zoom + posted to youtube
- suggest ~20 min talk from speaker (though can be flexible depending on speaker preferences). 
- ~40min for discussion: questions on science, suggestions / questions for future developments with SimPEG
- speakers can choose if they want questions throughout or to be held until the end 

This issue is for tracking the setup and kick-off of those! 
- [ ] name? 
    - SimPEG seminars
    - SimPEG research talks 
    - SimPEG science talks
- [ ] set up sendgrid for mail-outs (scoped out in #10)
- [ ] set up a curvenote project for abstracts & videos 
- [ ] identify seminar champion 
    - responsible for getting abstract, photo, bio from speakers each month + post on curvenote
    - create an associated notes document in curvenote for group notes during the presentation & discussion 
    - host & record on zoom + after include the video in the curvenote
    - social media send-out: twitter + mail out

**Comment by rowanc1** [comment]
Love this idea - and excited to tune in on these! My vote for the name is `SimPEG Seminars` 🚀

**Comment by lheagy** [comment]
I am going to close this now that we have the [SimPEG seminars](https://curvenote.com/@simpeg/seminars/) in action! Feel free to create a new issue if you have suggestions as to how to improve these in the future!
